spring.application.name=pigmyApp
server.port=1002
camel.servlet.mapping.context-path=/*
rest.api.base.url=/pigmy/v1
agent.resource.path=${rest.api.base.url}/agent

# ===============================
# Database Connection
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/pigmy
spring.datasource.username=root
spring.datasource.password=pavan123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate Settings
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.open-in-view=false